spring.application.name=agro-sensores
spring.datasource.url=jdbc:h2:mem:agrodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.security.secret=secret
api.security.expiration=2
